### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by NuruddeenSalis** [muety/readme-guestbook#1]

**Comment by muety** [comment]
Sorry, what do you mean with "Workflow"?

**Comment by NuruddeenSalis** [comment]
Sorry Was Trying To Track Workflow In Different Repos As A Newbie😀 It Fails Because I've Missed The Most Important Thing Which Is The Hello World Community Repo (Introduction)

**Comment by NuruddeenSalis** [comment]
**Mistake**
I've No Idea How It Works Back Then 
I Registered Community As An Individual

**Comment by NuruddeenSalis** [comment]
@muety
